export enum IconName {
  notifications = 'notifications',
  account_circle = 'account_circle',
  menu = 'menu',
  wifi = 'wifi',
  wifi_off = 'wifi_off',
  check = 'check',
  priority_high = 'priority_high',
  dvr = 'dvr',
  login = 'login',
  logout = 'logout',
  language = 'language',
  settings = 'settings',
  edit = 'edit',
  close = 'close',
  error = 'error',
  add = 'add',
  remove = 'remove',
  user_attributes = 'user_attributes',
}
