export enum PermissionName {
  all = 'all',
  devicesStart = 'devices:start',
  devicesStop = 'devices:stop',
  devicesReadStatus = 'devices:read-status',
  devicesReadEntities = 'devices:read-entity',
  devicesUpdateEntity = 'devices:update-entity',
  systemSettingsRead = 'system-settings:read',
  systemSettingsUpdate = 'system-settings:update',
  rolesCreate = 'roles:create',
  rolesRead = 'roles:read',
  rolesUpdate = 'roles:update',
  tariffsRead = 'tariffs:read',
  tariffsCreate = 'tariffs:create',
  tariffsUpdate = 'tariffs:update',
  tariffsRechargeDuration = 'tariffs:recharge-duration',
  usersRead = 'users:read',
  usersCreate = 'users:create',
  usersUpdate = 'users:update',
}
